### ISSUE TITLE
Suggestion: Link to third party themes

### ISSUE THREAD

**Issue by larshb** [mortnod/instabart#32]
Just wanted to give a heads up that there exist third party [themes](https://userstyles.org/styles/browse?search_terms=instabart) for Instabart. Maybe you'd like to reference it in your "andre snasne tjenester" section or something?

My [dark theme](https://userstyles.org/styles/158231/instabart-night) mostly overrides a few of [global.css](https://github.com/mortenvn/instabart/blob/master/css/global.scss) parameters. Hope you don't mind.

**Comment by mortenvn** [comment]
Cool! Thanks for the theme :)

Never heard of userstyles.org before. Is it basically a grease monkey community for styling websites?
